useAuth:
  useAccessToken:
    secretKey: R!@_SECRET_KEY
    expiration: 10d
  useRefreshToken:
    secretKey: R!@_SECRET_KEY
    expiration: 30d
server:
  port: 3000
  apiPrefix: api/v1
  swagger:
    title: Ria
    description: Ria apis for building ERP system
    version: 1.0
    api: /docs
    useAuth:
      username: ria
      password: ria
sequelizeOptions:
  database: ria
  autoLoadModels: true
  synchronize: false
  dialect: postgres
  username: ite_ria
  password: iteria
  sync:
    force: false
  define:
    underscored: true
    paranoid: true
    timestamps: true
    freezeTableName: false
  pool:
    min: 2
    max: 10
