useAuth:
  useCookies:
    expiration: 900000
  useAccessToken:
    secretKey: R!@_SECRET_KEY
    expiration: 15min
server:
  port: 3000
  apiPrefix: api/v1
  swagger:
    title: Juno
    description: Ria apis for building ERP system
    version: 1.0
    api: /docs
    useAuth:
      username: ria
      password: ria
database:
  name: ria
  autoLoadModels: true
  synchronize: false
  dialect: postgres
  username: ite_ria
  password: iteria
  sync:
    force: false
  define:
    underscored: true
    paranoid: true
    timestamps: true
    freezeTableName: false
  pool:
    min: 2
    max: 10
