useAuth:
  useAccessToken:
    secretKey: R!@_SECRET_KEY
    expiration: 30min
  useRefreshToken:
    secretKey: R!@_SECRET_KEY
    expiration: 30min
server:
  url: https://ite-ria.herokuapp.com/api/v1
  port: 3000
  apiPrefix: api/v1
  swagger:
    title: Ria
    description: Ria apis for building ERP system
    version: 1.0
    api: /docs
    useAuth:
      username: ria
      password: ria
sequelizeOptions:
  database: d25oiofqa43g2f
  autoLoadModels: true
  synchronize: false
  dialect: postgres
  dialectOptions:
    ssl:
      rejectUnauthorized: false
      require: true
  username: pnbodutggrkvav
  password: cce9abb16e5630dd06ee0cd0a306fc3e133cc932b4406972537110853af1c00f
  host: ec2-34-230-133-163.compute-1.amazonaws.com
  port: 5432
  sync:
    force: false
  define:
    underscored: true
    paranoid: true
    timestamps: true
    freezeTableName: false
  pool:
    min: 2
    max: 10
