export enum UserAuthExceptionCode {
  VERIFICATION_EMAIL_HAS_BEEN_SENT = '800',
  VERIFIED_USER = '801',
  INVALID_REGISTER_TOKEN = '802',
  UNVERIFIED_USER = '803',
  ALREADY_INVITED = '804',
  REGISTRATION_TOKEN_EXPIRED = '805',
  SAME_PASSWORD = '806',
  INACTIVE_USER = '807',
}
